/**
 * Most of these are generated by json2ts (http://json2ts.com/)
 * Manually update the definitions if needed
 */

// export type RESTModuleItemType =
//   | 'assignments'
//   | 'files'
//   | 'discussion_topics'
//   | 'pages'
//   | 'quizzes'
//   | 'external_tools';

export enum RESTModuleItemType {
  Assignments = 'assignments',
  Files = 'files',
  DiscussionTopics = 'discussion_topics',
  Pages = 'pages',
  Quizzes = 'quizzes',
  ExternalTools = 'external_tools',
}

export type RESTModuleItem =
  | RESTCanvasPage
  | RESTCanvasQuiz
  | RESTCanvasDisscusionTopic
  | RESTCanvasAssignment;

export type RESTModuleItemWithType =
  | (RESTCanvasPage & { type: RESTModuleItemType.Pages })
  | (RESTCanvasQuiz & { type: RESTModuleItemType.Quizzes })
  | (RESTCanvasDisscusionTopic & { type: RESTModuleItemType.DiscussionTopics })
  | (RESTCanvasAssignment & { type: RESTModuleItemType.Assignments });

export interface RESTCanvasPage {
  url: string;
  title: string;
  created_at: string;
  editing_roles: string;
  page_id: number;
  last_edited_by: {
    id: number;
    anonymous_id: string;
    display_name: string;
    avatar_image_url: string;
    html_url: string;
  };
  published: boolean;
  hide_from_students: boolean;
  front_page: boolean;
  html_url: string;
  todo_date: string | null;
  updated_at: string;
  locked_for_user: boolean;
  body: string;
}

export interface RESTCanvasQuiz {
  id: number;
  title: string;
  html_url: string;
  mobile_url: string;
  preview_url: string;
  description: string;
  quiz_type: string;
  assignment_group_id: number;
  time_limit: number;
  shuffle_answers: boolean;
  hide_results: string;
  show_correct_answers: boolean;
  show_correct_answers_last_attempt: boolean;
  show_correct_answers_at: Date;
  hide_correct_answers_at: Date;
  one_time_results: boolean;
  scoring_policy: string;
  allowed_attempts: number;
  one_question_at_a_time: boolean;
  question_count: number;
  points_possible: number;
  cant_go_back: boolean;
  access_code: string;
  ip_filter: string;
  due_at: Date;
  lock_at?: any;
  unlock_at: Date;
  published: boolean;
  unpublishable: boolean;
  locked_for_user: boolean;
  lock_info?: any;
  lock_explanation: string;
  speedgrader_url: string;
  quiz_extensions_url: string;
  permissions?: any;
  all_dates?: any;
  version_number: number;
  question_types: string[];
  anonymous_submissions: boolean;
}

export interface RESTCanvasDisscusionTopic {
  id: number;
  title: string;
  message: string;
  html_url: string;
  posted_at: Date;
  last_reply_at: Date;
  require_initial_post: boolean;
  user_can_see_posts: boolean;
  discussion_subentry_count: number;
  read_state: string;
  unread_count: number;
  subscribed: boolean;
  subscription_hold: string;
  assignment_id?: any;
  delayed_post_at?: any;
  published: boolean;
  lock_at?: any;
  locked: boolean;
  pinned: boolean;
  locked_for_user: boolean;
  lock_info?: any;
  lock_explanation: string;
  user_name: string;
  topic_children: number[];
  group_topic_children: { id: number; group_id: number }[];
  root_topic_id?: any;
  podcast_url: string;
  discussion_type: string;
  group_category_id?: any;
  attachments?: any;
  permissions: {
    attach: boolean;
  };
  allow_rating: boolean;
  only_graders_can_rate: boolean;
  sort_by_rating: boolean;
}

export interface RESTCanvasAssignment {
  all_dates?: any;
  allowed_attempts: number;
  allowed_extensions: string[];
  annotatable_attachment_id?: any;
  anonymous_grading: boolean;
  anonymous_submissions: boolean;
  assignment_group_id: number;
  assignment_visibility: number[];
  automatic_peer_reviews: boolean;
  can_submit: boolean;
  course_id: number;
  created_at: Date;
  description: string;
  discussion_topic?: any;
  due_at: Date;
  due_date_required: boolean;
  external_tool_tag_attributes?: any;
  final_grader_id: number;
  freeze_on_copy: boolean;
  frozen_attributes: string[];
  frozen: boolean;
  grade_group_students_individually: boolean;
  grader_comments_visible_to_graders: boolean;
  grader_count: number;
  grader_names_visible_to_final_grader: boolean;
  graders_anonymous_to_graders: boolean;
  grading_standard_id?: any;
  grading_type: string;
  group_category_id: number;
  has_overrides: boolean;
  has_submitted_submissions: boolean;
  html_url: string;
  intra_group_peer_reviews: boolean;
  lock_at: Date;
  lock_explanation: string;
  lock_info?: any;
  locked_for_user: boolean;
  max_name_length: number;
  moderated_grading: boolean;
  name: string;
  needs_grading_count: number;
  omit_from_final_grade: boolean;
  only_visible_to_overrides: boolean;
  overrides?: any;
  peer_review_count: number;
  peer_reviews_assign_at: Date;
  peer_reviews: boolean;
  points_possible: number;
  position: number;
  post_manually: boolean;
  post_to_sis: boolean;
  published: boolean;
  quiz_id: number;
  rubric?: any;
  score_statistics?: any;
  submission_types: string[];
  submission?: any;
  submissions_download_url: string;
  turnitin_enabled: boolean;
  turnitin_settings?: any;
  unlock_at: Date;
  unpublishable: boolean;
  updated_at: Date;
  use_rubric_for_grading: boolean;
  vericite_enabled: boolean;
  d: number;
}
