/**
 * Most of these are generated by json2ts (http://json2ts.com/)
 * Manually update the definitions if needed
 */

// export type RESTModuleItemType =
//   | 'assignments'
//   | 'files'
//   | 'discussion_topics'
//   | 'pages'
//   | 'quizzes'
//   | 'external_tools';

export enum RESTModuleItemType {
  Assignments = 'assignments',
  Files = 'files',
  DiscussionTopics = 'discussion_topics',
  Pages = 'pages',
  Quizzes = 'quizzes',
  ExternalTools = 'external_tools',
}

export type RESTModuleItem = RESTCanvasPage | RESTCanvasQuiz | RESTCanvasDisscusionTopic;

export type RESTModuleItemWithType =
  | (RESTCanvasPage & { type: RESTModuleItemType.Pages })
  | (RESTCanvasQuiz & { type: RESTModuleItemType.Quizzes })
  | (RESTCanvasDisscusionTopic & { type: RESTModuleItemType.DiscussionTopics });

export interface RESTCanvasPage {
  url: string;
  title: string;
  created_at: string;
  editing_roles: string;
  page_id: number;
  last_edited_by: {
    id: number;
    anonymous_id: string;
    display_name: string;
    avatar_image_url: string;
    html_url: string;
  };
  published: boolean;
  hide_from_students: boolean;
  front_page: boolean;
  html_url: string;
  todo_date: string | null;
  updated_at: string;
  locked_for_user: boolean;
  body: string;
}

export interface RESTCanvasQuiz {
  id: number;
  title: string;
  html_url: string;
  mobile_url: string;
  preview_url: string;
  description: string;
  quiz_type: string;
  assignment_group_id: number;
  time_limit: number;
  shuffle_answers: boolean;
  hide_results: string;
  show_correct_answers: boolean;
  show_correct_answers_last_attempt: boolean;
  show_correct_answers_at: Date;
  hide_correct_answers_at: Date;
  one_time_results: boolean;
  scoring_policy: string;
  allowed_attempts: number;
  one_question_at_a_time: boolean;
  question_count: number;
  points_possible: number;
  cant_go_back: boolean;
  access_code: string;
  ip_filter: string;
  due_at: Date;
  lock_at?: any;
  unlock_at: Date;
  published: boolean;
  unpublishable: boolean;
  locked_for_user: boolean;
  lock_info?: any;
  lock_explanation: string;
  speedgrader_url: string;
  quiz_extensions_url: string;
  permissions?: any;
  all_dates?: any;
  version_number: number;
  question_types: string[];
  anonymous_submissions: boolean;
}

export interface RESTCanvasDisscusionTopic {
  id: number;
  title: string;
  message: string;
  html_url: string;
  posted_at: Date;
  last_reply_at: Date;
  require_initial_post: boolean;
  user_can_see_posts: boolean;
  discussion_subentry_count: number;
  read_state: string;
  unread_count: number;
  subscribed: boolean;
  subscription_hold: string;
  assignment_id?: any;
  delayed_post_at?: any;
  published: boolean;
  lock_at?: any;
  locked: boolean;
  pinned: boolean;
  locked_for_user: boolean;
  lock_info?: any;
  lock_explanation: string;
  user_name: string;
  topic_children: number[];
  group_topic_children: { id: number; group_id: number }[];
  root_topic_id?: any;
  podcast_url: string;
  discussion_type: string;
  group_category_id?: any;
  attachments?: any;
  permissions: {
    attach: boolean;
  };
  allow_rating: boolean;
  only_graders_can_rate: boolean;
  sort_by_rating: boolean;
}
