/**
 * Generated by JSON2TS
 * Some types may not be accurate
 */
export interface Permissions {
  attach: boolean;
  update: boolean;
  reply: boolean;
  delete: boolean;
}

export interface Author {
  id: number;
  display_name: string;
  avatar_image_url: string;
  html_url: string;
  pronouns: string;
}

export interface RESTDiscussionTopic {
  id: number;
  assignment_id: null;
  root_topic_id: null;
  is_section_specific: boolean;
  delayed_post_at?: any;
  title: string;
  last_reply_at: Date;
  created_at: Date;
  posted_at: Date;
  position: number | null;
  podcast_has_student_posts: boolean;
  discussion_type: 'side_comment' | 'threaded';
  lock_at: Date | null;
  allow_rating: boolean;
  only_graders_can_rate: boolean;
  sort_by_rating: boolean;
  user_name: string;
  discussion_subentry_count: number;
  permissions: Permissions;
  require_initial_post?: any;
  user_can_see_posts: boolean;
  podcast_url?: any;
  read_state: string;
  unread_count: number;
  subscribed: boolean;
  attachments: any[];
  published: boolean;
  can_unpublish: boolean;
  locked: boolean;
  can_lock: boolean;
  comments_disabled: boolean;
  author: Author;
  html_url: string;
  url: string;
  pinned: boolean;
  group_category_id?: any;
  can_group: boolean;
  topic_children: any[];
  group_topic_children: any[];
  locked_for_user: boolean;
  message: string;
  subscription_hold: string;
  todo_date: Date | null;
}

export type RESTDiscussionTopicList = Array<RESTDiscussionTopic>;
